### ISSUE TITLE
About the trained adapter.

### ISSUE THREAD

**Issue by benjpau** [HLTCHKUST/KnowExpert#2]
Thanks for such excellent work.

I wonder if I only want to do task adapation on new dialogue dataset (similar to wow), do I just need to provide the appropriate `kadapter_path` and `cluster_path` when running the `task_adaptaion_w.sh`?

Also, could you please provide your trained `kadapter` models (I didn't find them in the onedrive) for the best results (KnowExpert_w in the paper)?
And, which topic_model did you use for the best results? `ctm_20k_topics_4` or `ctm_20k_new_hisres_4`? What is the difference between them?

Thanks a lot!

**Comment by yana-xuyan** [comment]
1. do I just need to provide the appropriate kadapter_path and cluster_path when running the task_adaptaion_w.sh?
Yes, I think so if you are saving kadapters in the same way as how I saved in `lm_finetuning_cluster.py`.
2. could you please provide your trained kadapter models (I didn't find them in the onedrive) for the best results (KnowExpert_w in the paper)?
Should be this one: https://hkustconnect-my.sharepoint.com/:f:/g/personal/yxucb_connect_ust_hk/Et9eSrPU_clOuAGwWb9-kTEByIQ3jtONH4_KsViLDHD53w?e=7yrwgz 
4. which topic_model did you use for the best results? ctm_20k_topics_4 or ctm_20k_new_hisres_4? What is the difference between them?
Actually, in `topic_model` folder, there are topic cluster predictions of the data samples in WoW (in `ctm_20k_new_hisres_4 `) and the knowledge corpus that we used (in `ctm_20k_topics_4 `). To train the adapters, we use  `ctm_20k_topics_4`, and we use `ctm_20k_new_hisres_4` to train the backbone on the downstream task. For evaluating on KGD task, we use `ctm_20k_SB_4`. Since this project has been a long time, I actually cannot find where I stored the saved topic model parameters. I'll let you know if I can find it at the end.

**Comment by benjpau** [comment]
Thank a lot!
