### ISSUE TITLE
masking file under data_utils is missing

### ISSUE THREAD

**Issue by wangxieric** [HLTCHKUST/KnowExpert#3]
In doc_reader.py
from src.data_utils.masking import split_span_masking
But no masking file is available.

**Comment by yana-xuyan** [comment]
Hi Eric, thank you for your interest! 

The python file `src/data_utils/masking.py` is for `MaskedDocReader` class, which is not involved in our proposed method. If you just want to reproduce our results, you can ignore this line by commenting it out.

This part was there because I explored this direction but did not dig deeply into it. If you are interested in this file, please drop your email address here. I can email that file to you. Just please remember to cite this paper if you use or refer to any code lines from it.
